# Generated by Django 4.0.6 on 2022-08-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='username',
            field=models.CharField(default='value', max_length=20),
        ),
    ]
